### ISSUE TITLE
Laguinho CLI

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/laguinho-cli#1]
_Issue destinada a discussão técnica de maneira geral, deverá ser quebrada em outras issues depois._

Discutimos aqui OpenDevUFCG/laguinho-api#31 e concordamos na criação de uma CLI para o laguinho. Ela terá funcionalidades de:

- Publicar dados a partir do seu repositório do seu projeto
- Consumir dados de outras pessoas

Em resumo `laguinho publish <dado>` e `laguinho get <dado>`.

**Agora vem as questões técnicas:**

**~1. Criaremos um repositório separado? Resposta: Sim! Estamos nele agora 😆~**
**~2. Qual linguagem será usada? Python é uma forte candidata. Resposta: PYTHON!~**
3. Que bibliotecas podemos utilizar?
4. Quais inspirações de CLI podemos estudar? Coloquem links aqui
5. Quais serão os passos iniciais

**Comment by JoseRenan** [comment]
Sobre as bibliotecas, se usarmos python, a [click](https://click.palletsprojects.com/en/7.x/) é muito boa e bem simples de usar. Se usarmos Go, o ideal é a lib [cobra](https://github.com/spf13/cobra).

Pra distribuir tem duas opções:
1. Em caso de python usar o setuptools e disponibilizar no pypi pra baixar via `pip` (não gosto dessa opção porque acho que tem treta de python2, python3, pip, virtualenv, mas tbm não sei se é um empecilho)
2. Gerar um executável e um script de instalação (nativamente no caso do Go, e no caso de python, usando [pyinstaller](https://www.pyinstaller.org/), ou alguma outra lib, só conheço o pyinstaller msm, se alguém tiver mais alguma ideia, manda link!!!!)

**Comment by thayannevls** [comment]
Precisa usar biblioteca pra fzr command line? No caso, se vale a pena

**Comment by JoseRenan** [comment]
Assim, fica bem organizado e já trata facilmente a parte de args e documentação, acho que só isso já vale a pena :thinking:

**Comment by thayannevls** [comment]
São pontos bons, mas tem desvantagens depender de libs e sua implementação, ainda mais as de python que geralmente são novinhas e não tem comunidade grande

**Comment by JoseRenan** [comment]
Qual das? Tipo o click já é bem estabelecida, inclusive o flask usa pra CLI deles, o pyinstaller que não sei direito, inclusive preciso de opiniões pq pra mim é o único motivo de ainda não bater o martelo pra usarmos python :(

**Comment by thayannevls** [comment]
hmm, já que o flask usa tudo bem então. É porque já usei algumas libs python q perdeu suporte, fico traumatizada XD

**Comment by thayannevls** [comment]
Não vejo vantagens técnicas que façam uma linguagem se sobrepor a outra no nosso caso. Então parte pra gente pensar no contexto, python talvez seja mais acessível para alunos da ufcg. Se for Go, dá uma oportunidade legal pro pessoal da UFCG ter um primeiro contato com a linguagem, só que significa que ter contribuintes é mais difícil.

Trade-off ai, make your choice @JoseRenan @paulojbleitao @eduhique @ArthurFerrao @grabowski74

**Comment by thayannevls** [comment]
Depois que os meninos comentarem, dá assign neles tbm @JoseRenan só pode dps q comenta

**Comment by JoseRenan** [comment]
> Não vejo vantagens técnicas que façam uma linguagem se sobrepor a outra no nosso caso.

Eu pensei no caso de distribuir mesmo, tipo, os trade-offs que temos com python é:
- pip (acredito que possa vir a ter problema dependendo da versão do python, pelo menos eu já tive 🤔 )
- snap (ajuda bastante pra usuários ubuntu, dificulta um pouco pra outros usuários linux e mata windows users)
- pyinstaller (gera executaveis pra todos os OSs, mas não conheço muito a biblioteca)

**Comment by thayannevls** [comment]
@JoseRenan sobre a versão do pip, acho que a comunidade já criou formas de overcome isso. 

Olha essa [cli](https://codesandbox.io/docs/importing#export-with-cli) do codesandbox, muito legal pra gente se basear.

Essa [parte](https://codesandbox.io/docs/importing#import-from-github) de importar com o github também é legal

**Comment by paulojbleitao** [comment]
Eu acho que não deve ter muito problema com o pip, pelo menos da minha experiência foram poucos os casos que tive problema com versionamento :thinking:

Como o próprio pip faz pra rodar?

**Comment by JoseRenan** [comment]
> Como o próprio pip faz pra rodar?

É pq tipo, o pip do python2 só baixa coisas do python2, o pip do python3 só baixa coisas do python3, pra alguns o do python3 já é o default, pra outros nn

**Comment by thayannevls** [comment]
@JoseRenan usaríamos **python3** para desenvolver, então qualquer possibilidade de suporte ao **python2** é descartada, não sendo um problema do **pip** em si. É comum que hoje em dia novos projetos usem **python3** e **pip3**, **python2** e **pip2** vai ficar obsoleto.

**Comment by paulojbleitao** [comment]
> É pq tipo, o pip do python2 só baixa coisas do python2, o pip do python3 só baixa coisas do python3, pra alguns o do python3 já é o default, pra outros nn

Sim, a minha dúvida é mais como o próprio pip roda. Ele tem um executável ou coisa assim? Porque se tiver a gente pode olhar como eles fazem

>  É comum que hoje em dia novos projetos usem python3 e pip3, python2 e pip2 vai ficar obsoleto.

Isso é verdade, tem um problema que a gente vê python 2 no curso né, mas a transição é bem tranquila

**Comment by thayannevls** [comment]
Vamos quebrar as issues pessoal

**Comment by fanny** [comment]
É, acho que Go podia ser uma opção mesmo, vejo muito use cases de cli nela, e acho que quanto ao aprendizado pelo que vi ela é bem compacta então acho que isso contribue pra não ter uma curva tão grande de aprendizado, e pelo que sei a comunidade encoraja muito você a usar **standard libraries**, assim não teríamos esse problema de manutenção de pacotes que a gnt usa. Quanto a atratividade em relação a novos contribuidores, eu sei que na graduação existe uma disciplina que usa, que é concorrente, essas pessoas poderiam se interessar.

**Comment by paulojbleitao** [comment]
> Quanto a atratividade em relação a novos contribuidores, eu sei que na graduação existe uma disciplina que usa, que é concorrente, essas pessoas poderiam se interessar.

O problema é que concorrente é bem pro final do curso, aí o projeto ficaria bem menos acessível mesmo

**Comment by JoseRenan** [comment]
Fechando issue em decorrencia dos pontos que foram discutidos em reunião aberta:

Bibliotecas: usaremos click para a CLI
Roadmap das versões até a 1.0 será planejado após a estruturação inicial do projeto
