### ISSUE TITLE
Criação do comando get

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/laguinho-cli#10]
Criação da estrutura do comando `get`, inicialmente, como estamos aguardando o back, o comando não executará nenhuma lógica muito específica, porém, ele terá no futuro a responsabilidade de baixar os dados do dataset passado por parametro localmente. Pra isso, o comando deve receber o parametro `name` que contém o identificador do dataset, por exemplo: `OpenDevUFCG/roadmap-cc`.

Tasks a serem feitas:
- [x] Criação do comando recebendo o [argumento](http://click.palletsprojects.com/en/7.x/arguments/#arguments) `name` e printando alguma mensagem como `Recuperando dados de ${name}...` ao executar
- [x] Adição da documentação no help sobre como funciona o comando `get`

**Comment by jessescn** [comment]
Posso tentar fazer?

**Comment by JoseRenan** [comment]
É sua ;)
