### ISSUE TITLE
Criação do comando publish

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/laguinho-cli#12]
Criação da estrutura do comando `publish`, esse comando será responsável por publicar datasets contidos no repositório no registry do laguinho, porém, inicialmente, como estamos aguardando o back, o comando vai ficar limitado a criar um arquivo `laguinho.json` com as informações passadas pelo usuário.

Essa issue pode ser dividida em 2 partes, onde a primeira definirei aqui:
- [ ] Criação do comando `publish` que não recebe nenhum argumento e exibe alguma mensagem indicando que o comando foi executado, tipo `Feature em desenvolvimento...` alguma coisa assim
- [ ] Adição da documentação no help sobre para que serve e como funciona o comando `publish`

A segunda parte é a criação de um "formulário interativo" como é feito no `npm init` perguntando as informações para adicionar no `laguinho.json` caso ele não exista, porém criarei outra issue pois pode ser feita paralelamente por outro contribuidor e depois adicionada ao comando

**Comment by ArthurFerrao** [comment]
Queria fazer essa, posso pegar?

**Comment by JoseRenan** [comment]
Yours ;)
