### ISSUE TITLE
Formulário interativo para criação do laguinho.json

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/laguinho-cli#13]
Ao rodar o comando `laguinho publish` (ver issue #12) a CLI deve verificar se existe o arquivo de metadados do dataset (`laguinho.json`), caso não haja, ele deve ser criado, essa task é pra criar uma função que seja um formulário interativo com prompts pedindo as informações ao usuário (algo como o `npm init` faz pra gerar o package.json) que pergunte as informações definidas no https://github.com/OpenDevUFCG/laguinho-api/issues/31#issuecomment-517514522:

- Nome do dataset (por exemplo `roadmap-cc`)
- URL do repositório onde o dataset se encontra (por exemplo `https://github.com/OpenDevUFCG/roadmap-cc`)
- Diretório, ou arquivo onde estão os dados que serão publicados (por default, publicará o diretório atual, mas pode ser `/data` por exemplo, que é uma pasta dentro do diretório atual onde estão os dados)
- Autores ou maintaineres (pode ser uma lista de nomes separado por virgula, não sei... podemos discutir isso aqui...)
- Formato dos arquivos dos dados (a principio vamos supor que todos os dados estão em um único tipo de arquivo...)
- Flag indicando se os dados são contribuíveis (se eles podem ser atualizados pela comunidade...)

Esses items devem gerar um arquivo `laguinho.json` no diretório atual onde o comando foi executado. Ele ainda pode sofrer modificações na sua estrutura, mas inicialmente podemos considerar que ele é no formato:

```json
{
    "name": "",
    "url": "",
    "path" : "",
    "maintainers": ["", ""],
    "format": "csv|json",
    "contributable": "true|false"
}
```

pra fazer isso, acho que é só usar [essas paradas aqui do click](https://click.palletsprojects.com/en/7.x/prompts/).

**Comment by JoseRenan** [comment]
Vcs acham que o json nesse formato tá ok?

**Comment by JoseRenan** [comment]
cc @thayannevls @paulojbleitao

**Comment by paulojbleitao** [comment]
Acho que tá bom assim, pelo menos não me parece agora que está faltando algo 🤔

Eu acho que alguns dos campos podem ser opcionais, tipo `maintainers` e `contributable`

**Comment by thayannevls** [comment]
adicionar versão, talvez?

**Comment by JoseRenan** [comment]
A gente tinha definido que não ia versionar a princípio, ia considerar o HEAD do master por enquanto

**Comment by jessescn** [comment]
Posso tentar essa issue?

**Comment by thayannevls** [comment]
Não precisa versionar, só adicionar versão msm @JoseRenan

**Comment by JoseRenan** [comment]
> Não precisa versionar, só adicionar versão msm @JoseRenan

Aí a gente vai estar iludindo os usuários :'( kkkkkkk

**Comment by JoseRenan** [comment]
> Posso tentar essa issue?

a s s i g n e d
