### ISSUE TITLE
Definir versão do python necessária no setup.py

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/laguinho-cli#15]
No setuptools é possível definir a versão do python necessária pra o pacote ser instalado, como o laguinho só dará suporte ao python 3, é bom que definamos no `setup.py` pra caso a pessoa tente instalar a CLI utilizando uma versão abaixo, o pip não permita.

Links úteis de como fazer isso:
https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py
https://stackoverflow.com/questions/37216560/how-can-i-specify-a-python-version-using-setuptools

**Comment by lucasaarcoverde** [comment]
Oii, posso fazer essa?

**Comment by JoseRenan** [comment]
Vai que é tua
