### ISSUE TITLE
Adição do CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/laguinho-cli#2]
Criação de código de conduta com base nos outros repositórios do OpenDev.
Acredito que todos os repositórios da org possuem o mesmo código de conduta.

**Comment by JoseRenan** [comment]
@thayannevls pode me confirmar? kkkkkkkkkk

**Comment by thayannevls** [comment]
kkkk é isso msm, aliás, pode criar com template de outro repo todos os docs do repo

**Comment by JoseRenan** [comment]
Marcando como duplicate do #6
