### ISSUE TITLE
Integrar publish com laguinho-api

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/laguinho-cli#21]
Pessoas!!!! como pudemos ver no https://github.com/OpenDevUFCG/laguinho-api/pull/45 , habemus publish no backend, fazendo com que agora possamos concluir a parte que não coloquei na #12 que era a de enviar o dataset para o laguinho-api.

Quem pegar essa issue deve submeter os metadados do dataset que serão publicados para o `POST /datasets` do laguinho API. 

As informações de como rodar o servidor e etc constam no repositório da API.

**Comment by lucasaarcoverde** [comment]
Oii, posso fazer?

**Comment by JoseRenan** [comment]
Pode sim!!

**Comment by lucasaarcoverde** [comment]
Estava resolvendo a issue e notei que a API_URL precisa ser global, tanto para o get utilizar quanto para o publish, mas não sei uma forma "legal" de colocar globalmente, alguma dica?

**Comment by JoseRenan** [comment]
Eu sinceramente não tinha pensado nisso ainda kkkkkkkkkkk tipo, o que geralmente é feito é botar variável de ambiente, mas a questão é que pode ter uma release do laguinho instalada na minha máquina e ela começar a usar a URL que tá na variável de ambiente de desenvolvimento... daí tem de pensar em alguma coisa pra resolver isso 🤔

**Comment by JoseRenan** [comment]
Talvez seja uma solução considerar que sempre que usarmos o laguinho-dev está rodando em desenvolvimento, o laguinho-dev executa a CLI pelo main, enquanto a versão de release vai rodar a partir do setup.py, daí a gente pode definir alguma flag com isso, no __main__ a gente bota uma variável global DEVELOPMENT pra true, e daí significa que ele deve procurar uma variável de ambiente pra definir qual a global URL 🤔 nusei acho que isso resolve

**Comment by lucasaarcoverde** [comment]
Massa, vou tentar fazer isso então. qualquer coisa pergunto 💃
