### ISSUE TITLE
Criação de função que baixa datasets

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/laguinho-cli#22]
Enquanto ainda não temos o endpoint de recuperar metadados de dataset por nome (acompanhar status da issue https://github.com/OpenDevUFCG/laguinho-api/issues/48), ainda não temos como botar o comando `laguinho get <nomedodataset>` para funcionar, porém, nada impede que criemos uma função que baixa datasets passados os metadados desse dataset...

Quem pegar essa issue deve criar uma função (algo tipo `download_dataset(metadata)`) e ela deve baixar no diretório atual todo o conteúdo da pasta definida no atributo `path` dos metadados (ver #20 para saber a estrutura completa do metadata) diretamente do repositório indicado no atributo `url` dos metadados.

Pra facilitar nossa vida, o github disponibiliza [essa api](https://developer.github.com/v3/repos/contents/#get-contents) que dá um download URL pra cada arquivo de uma pasta do repositório (uma mão na roda não é mesmo??? kkkkk)

**Comment by jessescn** [comment]
mim dê papai
