### ISSUE TITLE
Validação dos inputs no laguinho publish

### ISSUE THREAD

**Issue by jessescn** [OpenDevUFCG/laguinho-cli#25]
Enquanto eu estava trabalhando na função de baixar o dataset do laguinho get, eu percebi duas fragilidades que podem acontecer dentro do menu interativo do laguinho publish, são elas: 

- o atributo _path_ não deve poder terminar com "/" 
-  a URL deve possuir a substring 'github.com'

Imagino que o melhor é tratar esses dados na CLI dentro do menu interativo, ao invés de tratar na API ou até mesmo no comando GET, já que eu imagino que ambos devem esperar dados corretos.

**Comment by ArthurFerrao** [comment]
Também tem a checagem se existe no git aquele diretório da url digitada. Em caso do usuario passar algo errado, ou errar alguma coisa ao digitar a url.

**Comment by jessescn** [comment]
@JoseRenan já que ninquem se propôs a fazer, posso pegar ela pra fazer?

**Comment by JoseRenan** [comment]
Vai que é tua KKKK
