### ISSUE TITLE
Reformular README do projeto

### ISSUE THREAD

**Issue by jessescn** [OpenDevUFCG/laguinho-cli#33]
**Descrição da melhoria:**
Definir de forma mais clara qual o objetivo do projeto, além do funcionamento geral de por quê o projeto existe e qual problema ele tenta resolver, além de coisas bonitas e tudo mais

**Como ela pode ser implementada:**
Alterando o arquivo README e pedindo pull request para a branch master. lembrando que qualquer dúvida pode perguntar para @JoseRenan @jessescn ou @paulojbleitao.

**Comment by paulojbleitao** [comment]
Uma possível inspiração é a [documentação do npm](https://docs.npmjs.com/about-npm). Olhando por cima, a seção "Use npm to..." parece uma boa ideia, exemplificando os casos de uso
